#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Fabric-X Committer sidecar container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: container/rm
  when: not committer_use_bin

- name: Clean Fabric-X Committer Sidecar volumes
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: sidecar/container/clean
  when: not committer_use_bin

- name: Stop Fabric-X Committer sidecar binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: bin/stop
  when: committer_use_bin

- name: Remove Fabric-X Committer sidecar binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: bin/rm
  when: committer_use_bin

- name: Clean Fabric-X Committer Sidecar data
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: sidecar/bin/clean
  when: committer_use_bin

- name: Remove Fabric-X Committer sidecar configuration files
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: config/rm
