#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Install {{ committer_bin_name }}
  vars:
    bin_service_instances: "{{ committer_service_instances }}"
    bin_go_package: "{{ committer_bin_package }}@{{ committer_git_commit }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.bin
    tasks_from: go/multiplatform_install
