#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Start the Fabric-X Committer validator persistence binaries
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: validator/bin/start
  when: committer_component_type == 'validator'

- name: Start the Fabric-X Committer signature verifiers binaries
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: verifier/bin/start
  when: committer_component_type == 'verifier'

- name: Start the Fabric-X Committer coordinator binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: coordinator/bin/start
  when: committer_component_type == 'coordinator'

- name: Start Fabric-X Committer sidecar binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: sidecar/bin/start
  when: committer_component_type == 'sidecar'
