#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch loadgen logs from container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.loadgen
    tasks_from: container/fetch_logs
  when: not loadgen_use_bin

- name: Fetch loadgen logs from binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.loadgen
    tasks_from: bin/fetch_logs
  when: loadgen_use_bin
