#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Stop Fabric-X Loadgen container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.loadgen
    tasks_from: container/stop
  when: not loadgen_use_bin

- name: Stop Fabric-X Loadgen binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.loadgen
    tasks_from: bin/stop
  when: loadgen_use_bin
