#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Fabric-X Loadgen container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.loadgen
    tasks_from: container/rm
  when: not loadgen_use_bin

- name: Stop Fabric-X Loadgen binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.loadgen
    tasks_from: bin/stop
  when: loadgen_use_bin

- name: Remove Fabric-X Loadgen binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.loadgen
    tasks_from: bin/rm
  when: loadgen_use_bin

- name: Remove Fabric-X Loadgen binary configuration files
  ansible.builtin.include_role:
    name: hyperledger.fabricx.loadgen
    tasks_from: config/rm
