#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Start Postgres Exporter Sidecar container
  vars:
    container_name: "{{ postgres_exporter_container_name }}"
    container_image: "{{ postgres_exporter_image }}"
    container_command: >-
      --web.listen-address=:{{ postgres_exporter_port }}
    container_ports:
      - "{{ postgres_exporter_port }}:{{ postgres_exporter_port }}"
    container_env:
      DATA_SOURCE_NAME: "{{ postgres_exporter_data_source_name }}"
    container_wait_until_running: true
    container_wait_port: "{{ postgres_exporter_port }}"
    container_run_as_host_user: true
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: start
