#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Fabric-X Orderer config directory
  ansible.builtin.file:
    path: "{{ orderer_remote_config_dir }}"
    state: absent
