#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch the Fabric-X Committer logs
  hosts: "{{ target_hosts | default('fabric-x-committer') }}:&fabric-x-committer"
  tasks:
    - name: Fetch the Fabric-X Committer logs
      ansible.builtin.include_role:
        name: hyperledger.fabricx.committer
        tasks_from: fetch_logs
