#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Transfer Fabric-X Committer binaries
  hosts: "{{ target_hosts | default('fabric-x-committer') }}:&fabric-x-committer"
  tasks:
    - name: Transfer the Fabric-X Committer binaries
      ansible.builtin.include_role:
        name: hyperledger.fabricx.committer
        tasks_from: bin/transfer
      when: committer_use_bin is defined and committer_use_bin
