#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Start cryptogen as container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.cryptogen
    tasks_from: container/start
  when: not cryptogen_use_bin

- name: Start cryptogen as binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.cryptogen
    tasks_from: bin/start
  when: cryptogen_use_bin
