#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Clone the Fabric-X Orderer repository
  vars:
    git_uri: "{{ armageddon_git_uri }}"
    git_dir: "{{ armageddon_git_dir }}"
    git_commit: "{{ armageddon_git_commit }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.git
    tasks_from: clone

- name: Build armageddon
  vars:
    bin_name: "{{ armageddon_bin_name }}"
    bin_source_code_path: "{{ armageddon_source_code_dir }}"
    bin_output_dir: "{{ cli_bin_dir }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.bin
    tasks_from: go/build
