#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Stop the Postgres DB containers
  ansible.builtin.include_role:
    name: hyperledger.fabricx.postgres
    tasks_from: container/stop
  when: committer_use_postgres

- name: Stop the Yugabyte DB containers
  ansible.builtin.include_role:
    name: hyperledger.fabricx.yugabyte
    tasks_from: container/stop
  when: not committer_use_postgres
