#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove the Postgres DB containers
  ansible.builtin.include_role:
    name: hyperledger.fabricx.postgres
    tasks_from: container/rm
  when: committer_use_postgres

- name: Clean Postgres DB volumes
  ansible.builtin.include_role:
    name: hyperledger.fabricx.postgres
    tasks_from: container/clean
  when: committer_use_postgres

- name: Remove the Yugabyte DB containers
  ansible.builtin.include_role:
    name: hyperledger.fabricx.yugabyte
    tasks_from: container/rm
  when: not committer_use_postgres

- name: Clean Yugabyte DB volumes
  ansible.builtin.include_role:
    name: hyperledger.fabricx.yugabyte
    tasks_from: container/clean
  when: not committer_use_postgres

- name: Remove Yugabyte configuration files
  ansible.builtin.include_role:
    name: hyperledger.fabricx.yugabyte
    tasks_from: config/rm
  when: not committer_use_postgres
