#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
- name: Stop the Postgres Exporter Sidecar container
  vars:
    container_name: "{{ postgres_exporter_container_name }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: stop
