#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Start Fabric-X Committer verifier container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: verifier/container/start
  when: not committer_use_bin

- name: Start Fabric-X Committer verifier binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: verifier/bin/start
  when: committer_use_bin
