#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Teardown Fabric-X Committer verifier container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: container/rm
  when: not committer_use_bin

- name: Stop Fabric-X Committer verifier binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.committer
    tasks_from: bin/stop
  when: committer_use_bin
