#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Create config build output directory
  ansible.builtin.file:
    path: "{{ configtxgen_output_dir }}"
    state: directory
    mode: "0o750"

- name: Create configtxgen.yaml from template
  vars:
    cryptogen_artifacts_dir: "{{ configtxgen_cryptogen_artifacts_dir if configtxgen_use_bin else configtxgen_cryptogen_docker_artifacts_dir }}"
    idemixgen_artifacts_dir: "{{ configtxgen_idemixgen_artifacts_dir if configtxgen_use_bin else configtxgen_idemixgen_docker_artifacts_dir }}"
    armageddon_artifacts_dir: "{{ configtxgen_armageddon_artifacts_dir if configtxgen_use_bin else configtxgen_armageddon_docker_artifacts_dir }}"
  ansible.builtin.template:
    src: configtx.yaml.j2
    dest: "{{ configtxgen_output_dir }}/{{ configtxgen_config_file }}"
    mode: "0o644"
