#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove the Fabric-X Committer config directory
  ansible.builtin.file:
    path: "{{ committer_remote_config_dir }}"
    state: absent
