#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch the logs from Fabric-X Orderer
  hosts: "{{ target_hosts | default('fabric-x-orderers') }}:&fabric-x-orderers"
  tasks:
    - name: Fetch the logs from the Fabric-X Orderer components
      ansible.builtin.include_role:
        name: hyperledger.fabricx.orderer
        tasks_from: fetch_logs
