#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check if chrony is already installed
  ansible.builtin.stat:
    path: "/usr/bin/chronyc"
  register: yugabyte_check_chrony

- name: Check if chrony is available as package
  ansible.builtin.command: "{{ ansible_pkg_mgr }} list chrony"
  register: yugabyte_chrony_available
  changed_when: false
  failed_when: false
  when: not yugabyte_check_chrony.stat.exists

- name: Install chrony
  become: true
  ansible.builtin.package:
    name: chrony
    state: present
  when: not yugabyte_check_chrony.stat.exists and yugabyte_chrony_available.rc == 0

- name: Start chrony
  ansible.builtin.service:
    name: chronyd
    state: started
    enabled: true
  when: yugabyte_check_chrony.stat.exists or (yugabyte_chrony_available is defined and yugabyte_chrony_available.rc == 0)
