#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove the Yugabyte DB containers
  ansible.builtin.include_role:
    name: hyperledger.fabricx.yugabyte
    tasks_from: container/rm

- name: Clean Yugabyte DB volumes
  ansible.builtin.include_role:
    name: hyperledger.fabricx.yugabyte
    tasks_from: container/clean

- name: Remove Yugabyte configuration files
  ansible.builtin.include_role:
    name: hyperledger.fabricx.yugabyte
    tasks_from: config/rm
