#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Prometheus config directory
  ansible.builtin.file:
    path: "{{ prometheus_remote_config_dir }}"
    state: absent
