#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Ensure Prometheus directory exists
  ansible.builtin.file:
    path: "{{ prometheus_remote_config_dir }}"
    state: directory
    mode: "0o755"

- name: Generate prometheus.yaml
  ansible.builtin.template:
    src: "prometheus_template.yaml.j2"
    dest: "{{ prometheus_remote_config_dir }}/prometheus.yml"
    mode: "0o644"
