#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Find the container client to use
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: get_container_client
  when: container_client == ''

- name: Remove container with podman client
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: podman/rm
  when: container_client == 'podman'

- name: Remove container with container client
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: docker/rm
  when: container_client == 'docker'
