#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Show Docker command to run
  ansible.builtin.debug:
    msg: "{{ container_command }}"
  when:
    - not container_omit_logs
    - not container_run_detach_mode

- name: Find the container client to use
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: get_container_client
  when: container_client == ''

- name: Start container with podman
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: podman/start
  when: container_client == 'podman'

- name: Start container with docker
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: docker/start
  when: container_client == 'docker'
