#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Create config build output directory
  ansible.builtin.file:
    path: "{{ configtxgen_output_dir }}"
    state: directory
    mode: "0o750"

- name: Define mandatory Docker mounts
  ansible.builtin.set_fact:
    configtxgen_docker_volumes:
      - "{{ configtxgen_output_dir }}:{{ configtxgen_docker_output_dir }}"
      - "{{ configtxgen_cryptogen_artifacts_dir }}:{{ configtxgen_cryptogen_docker_artifacts_dir }}"
      - "{{ configtxgen_armageddon_artifacts_dir }}:{{ configtxgen_armageddon_docker_artifacts_dir }}"

- name: Add volume for idemixgen CA
  vars:
    idemixgen_artifacts_volume: "{{ configtxgen_idemixgen_artifacts_dir }}:{{ configtxgen_idemixgen_docker_artifacts_dir }}"
  ansible.builtin.set_fact:
    configtxgen_docker_volumes: "{{ configtxgen_docker_volumes + [idemixgen_artifacts_volume] }}"
  when: configtxgen_idemixgen_artifacts_dir is exists

- name: Generate the genesis block with configtxgen as container
  vars:
    container_name: "{{ configtxgen_container_name }}"
    container_image: "{{ configtxgen_image }}"
    container_command: >-
      {{ configtxgen_bin_name }}
      -channelID {{ configtxgen_channel_id }}
      -profile {{ configtxgen_profile_id }}
      -configPath {{ configtxgen_docker_output_dir }}
      --outputBlock {{ configtxgen_docker_output_dir }}/{{ configtxgen_channel_id }}_block.pb
    container_volumes: "{{ configtxgen_docker_volumes }}"
    container_run_detach_mode: false
    container_run_as_host_user: true
    container_autoremove: true
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: start
