#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Start Yugabyte master DB container
  ansible.builtin.include_role:
    name: hyperledger.fabricx.yugabyte
    tasks_from: distributed/master/start
  when: yugabyte_component_type is defined and yugabyte_component_type == "master"

- name: Start Yugabyte Tablet Servers containers
  ansible.builtin.include_role:
    name: hyperledger.fabricx.yugabyte
    tasks_from: distributed/tablet/start
  when: yugabyte_component_type is defined and yugabyte_component_type == "tablet"
