#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Wipe Fabric-X Loadgen
  hosts: "{{ target_hosts | default('load-generators') }}:&load-generators"
  tasks:
    - name: Wipe Fabric-X Loadgen
      ansible.builtin.include_role:
        name: hyperledger.fabricx.loadgen
        tasks_from: wipe
