#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove Fabric-X Loadgen container
  vars:
    container_name: "sc-loadgen-{{ inventory_hostname }}"
    container_image: "{{ loadgen_image }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: rm
