#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Install {{ configtxgen_bin_name }}
  vars:
    bin_output_dir: "{{ cli_bin_dir }}"
    bin_go_package: "{{ configtxgen_bin_package }}@{{ configtxgen_git_commit }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.bin
    tasks_from: go/install
