#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Clone the Fabric repository
  vars:
    git_uri: "{{ cryptogen_git_uri }}"
    git_dir: "{{ cryptogen_git_dir }}"
    git_commit: "{{ cryptogen_git_commit }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.git
    tasks_from: clone

- name: Build {{ cryptogen_bin_name }}
  vars:
    bin_name: "{{ cryptogen_bin_name }}"
    bin_source_code_path: "{{ cryptogen_source_code_dir }}"
    bin_output_dir: "{{ cli_bin_dir }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.bin
    tasks_from: go/build
