#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Ensure that the cryptogen output folder is clean
  ansible.builtin.file:
    state: absent
    path: "{{ cryptogen_output_dir }}"

- name: Start the cryptogen binary
  vars:
    bin_run_with_tmux: false
    bin_remote_dir: "{{ cli_bin_dir }}"
    bin_command: >-
      {{ cryptogen_bin_name }} generate
      --config={{ cryptogen_config_dir }}/{{ cryptogen_config_file }}
      --output={{ cryptogen_output_dir }}
    bin_collect_logs: false
  ansible.builtin.include_role:
    name: hyperledger.fabricx.bin
    tasks_from: start

- name: Find all TLS CA certs
  ansible.builtin.find:
    paths: "{{ cryptogen_output_dir }}"
    patterns: "tlsca*.pem"
    depth: 4
    recurse: true
  register: tlsca_cert_files

- name: Combine all TLS CA certs in ca-certs.pem
  ansible.builtin.shell: >-
    cat {{ tlsca_cert_files.files | map(attribute='path') | join(' ') }}
    > {{ cryptogen_output_dir }}/ca-certs.pem
  register: result
  changed_when: result.rc != 0
  when: tlsca_cert_files.files | length > 0
