#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch the logs from the Prometheus container
  vars:
    container_name: "{{ prometheus_container_name }}"
    container_logs_file: "{{ prometheus_container_name }}_logs.txt"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: fetch_logs
