#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Fetch the logs from the Fabric-X Orderer consenters
  ansible.builtin.include_role:
    name: hyperledger.fabricx.orderer
    tasks_from: orderer_consenter/fetch_logs
  when: orderer_component_type == 'consenter'

- name: Fetch the logs from the Fabric-X Orderer batchers
  ansible.builtin.include_role:
    name: hyperledger.fabricx.orderer
    tasks_from: orderer_batcher/fetch_logs
  when: orderer_component_type == 'batcher'

- name: Fetch the logs from the Fabric-X Orderer assemblers
  ansible.builtin.include_role:
    name: hyperledger.fabricx.orderer
    tasks_from: orderer_assembler/fetch_logs
  when: orderer_component_type == 'assembler'

- name: Fetch the logs from the Fabric-X Orderer routers
  ansible.builtin.include_role:
    name: hyperledger.fabricx.orderer
    tasks_from: orderer_router/fetch_logs
  when: orderer_component_type == 'router'
