#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Ensure verifier-client config directory exists
  ansible.builtin.file:
    path: "{{ loadgen_remote_config_dir }}"
    state: directory
    mode: "0o750"

- name: Generate the config for the Fabric-X Loadgen for the Fabric-X Committer Verifiers
  vars:
    loadgen_config_dir: "{{ loadgen_remote_config_dir if loadgen_use_bin else loadgen_docker_config_dir }}"
    loadgen_use_key: true
  ansible.builtin.template:
    src: "verifier-client.yaml.j2"
    dest: "{{ loadgen_remote_config_dir }}/{{ loadgen_config_file }}"
    mode: "0o644"

- name: Generate Loadgen keys
  ansible.builtin.include_role:
    name: hyperledger.fabricx.loadgen
    tasks_from: config/generate_key
