#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove the Yugabyte config directory
  ansible.builtin.file:
    path: "{{ yugabyte_remote_config_dir }}/init"
    state: absent
