#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Remove the Postgres DB container
  vars:
    container_name: "{{ postgres_container_name }}"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.container
    tasks_from: rm

- name: Remove the Postgres DB exporter container
  vars:
    postgres_exporter_container_name: "{{ postgres_container_name }}_exporter"
  ansible.builtin.include_role:
    name: hyperledger.fabricx.postgres_exporter
    tasks_from: teardown
  when:
    - postgres_exporter_port is defined
