#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Check that the private key path has been defined
  ansible.builtin.fail:
    msg: "No private key path has been defined, but required to build the binary. Set it via 'openssl_private_key_path'."
  when: openssl_private_key_path is not defined

- name: Check that the public key path has been defined
  ansible.builtin.fail:
    msg: "No private key path has been defined, but required to build the binary. Set it via 'openssl_cert_path'."
  when: openssl_cert_path is not defined

- name: Generate ECDSA private key
  ansible.builtin.command: >-
    openssl ecparam
    -name {{ openssl_ecdsa_curve }}
    -genkey
    -noout
    -out {{ openssl_private_key_path }}
  args:
    creates: "{{ openssl_private_key_path }}"

- name: Generate CSR
  ansible.builtin.command: >-
    openssl req
    -new
    -key {{ openssl_private_key_path }}
    -subj "/C=US/ST=State/L=City/O=Organization/CN=example.com"
    -out {{ openssl_csr_path }}
  args:
    creates: "{{ openssl_csr_path }}"

- name: Export ECDSA public key in PEM format
  ansible.builtin.command: >
    openssl x509
    -req
    -days 365
    -in {{ openssl_csr_path }}
    -signkey {{ openssl_private_key_path }}
    -out {{ openssl_cert_path }}
  args:
    creates: "{{ openssl_cert_path }}"
