#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Install openssl on Linux
  become: true
  ansible.builtin.package:
    name:
      - openssl
    state: present
  when: ansible_facts.os_family in ['Debian', 'RedHat']
- name: Install openssl on macOS
  community.general.homebrew:
    name:
      - openssl
    state: present
  when: ansible_facts.os_family == 'Darwin'
