#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

# configtxgen image
configtxgen_registry_endpoint: "{{ lookup('env', 'CONFIGTXGEN_REGISTRY_ENDPOINT') or 'docker.io/hyperledger' }}"
configtxgen_image_name: "fabric-x-tools"
configtxgen_image_tag: "latest"
configtxgen_image: "{{ configtxgen_registry_endpoint }}/{{ configtxgen_image_name }}:{{ configtxgen_image_tag }}"
configtxgen_container_name: "configtxgen"

# configtxgen bin
configtxgen_git_uri: "https://github.com/hyperledger/fabric-x-common.git"
configtxgen_git_dir: "{{ source_code_dir }}/fabric-x-common"
configtxgen_git_commit: "c15db56a338270210cc765d0a3ec4041b091df26"
configtxgen_source_code_dir: "{{ configtxgen_git_dir }}/cmd/configtxgen"
configtxgen_bin_package: "github.com/hyperledger/fabric-x-common/cmd/configtxgen"
configtxgen_bin_name: "configtxgen"

# configtxgen paths/locations
configtxgen_output_dir: "{{ config_build_dir }}/configtxgen-artifacts"
configtxgen_cryptogen_artifacts_dir: "{{ config_build_dir }}/cryptogen-artifacts"
configtxgen_idemixgen_artifacts_dir: "{{ config_build_dir }}/idemixgen-artifacts"
configtxgen_armageddon_artifacts_dir: "{{ config_build_dir }}/armageddon-artifacts"
configtxgen_docker_output_dir: "/tmp/configtxgen-artifacts"
configtxgen_cryptogen_docker_artifacts_dir: "/tmp/cryptogen-artifacts"
configtxgen_idemixgen_docker_artifacts_dir: "/tmp/idemixgen-artifacts"
configtxgen_armageddon_docker_artifacts_dir: "/tmp/armageddon-artifacts"
configtxgen_armageddon_binpb_file: "shared_config.binpb"
configtxgen_config_file: "configtx.yaml"

# configtxgen misc
configtxgen_use_bin: "{{ use_bin | default(false) }}"
configtxgen_channel_id: "{{ channel_id }}"
configtxgen_profile_id: "OrgsChannel"
configtxgen_orderers_by_org: {}
configtxgen_peers_by_org: {}
