#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Start Fabric-X Orderer router containers
  ansible.builtin.include_role:
    name: hyperledger.fabricx.orderer
    tasks_from: orderer_router/container/start
  when: not orderer_use_bin

- name: Start Fabric-X Orderer router binary
  ansible.builtin.include_role:
    name: hyperledger.fabricx.orderer
    tasks_from: orderer_router/bin/start
  when: orderer_use_bin
