#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Start docker daemon
  become: true
  ansible.builtin.service:
    name: hyperledger.fabricx.container
    state: started
    enabled: true
  when: ansible_facts.os_family in ['Debian', 'RedHat']
