#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Stop container
  community.docker.docker_container:
    name: "{{ container_name }}"
    state: stopped
