#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

- name: Clean the Yugabyte DB volume
  ansible.builtin.file:
    path: "{{ yugabyte_remote_config_dir }}/data"
    state: absent
